### ISSUE TITLE
As a developer, I want to understand the GitHub workflow so that I can commit code

### ISSUE THREAD

**Issue by maxxwizard** [bumgardnera07/Wagers#13]
- does a completed PR tied to a issue resolve the GitHub issue?

**Comment by bumgardnera07** [comment]
I think Pull Request -> Code Review -> Merge should be sufficient for issues that need code submission to complete. We'll need to determine who the reviewer is, but that can be assigned when the issue is assigned, or can be someone solved with CI against the developer branch if we identify a threshold for testing coverage/ acceptance.

For research issues, I think we can just expect a 1 sprint commitment for each issue. Issues should be recapped during sprint review retro and then if more research is necessary, the issue can be reopened/ extended or a new issue can be created.

**Comment by maxxwizard** [comment]
@bumgardnera07 and I exercised the PR merge strategy of: personal -> develop -> master.
