### ISSUE TITLE
"hello world" on watchOS platform

### ISSUE THREAD

**Issue by maxxwizard** [bumgardnera07/Wagers#9]
**Acceptance Criteria:**
- App gets data from dedicated backend via network.
- App says "hello world."

**Comment by bumgardnera07** [comment]
I ran into a few issues/ complications working on this user story:

1) Flutter doesn't currently support the platforms that any wearable app is created on. In other words, if you add a WatchKit device to your app build, or WearOS device, 'Flutter Run' will not work. The way around this appears to build be to build these parts of the project in native and then link them to the flutter project, which is obviously more steps. The reason for this is that Flutter doesn't currently support Bitcode, though it is marked as a severe priority issue on the Flutter github.

2) Fitbit has no 'native', but apps can be created for it using Javascript, VSS, and SVG. SDK is here: https://dev.fitbit.com/. I lot of unknowns for building fitbit support, but it appears to be more limited than the other 'wearables'.

3) Because WatchOS apps can't be built in flutter, the only options are either building them in non-native, which isn't preferred because it will be clunky and slow, or building them in XCode, which is a hurdle for me right now because XCode only runs on Apple OS. I'll need to look into some options here to see how I can build this (considering a MAC emulator or cloud9.io or something like that), but right now the only wearable I can develop for is WearOS (Android) and I can only run on an emulator, since I don't have an android smartwatch.

**Comment by maxxwizard** [comment]
we're going with Flutter & Firebase to support 2 primary platforms iOS and Android.
